/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deadly21;

import java.awt.Color;

/**
 *
 * @Galvys Rodriguez
 */
public class Avisos extends javax.swing.JDialog {

    /**
     * Creates new form Avisos
     */
    public Avisos(java.awt.Frame parent, boolean modal,String mensaje, String mensaje2) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        setLocationRelativeTo(null);
        avisosText.setText(mensaje);
        avisosText1.setText(mensaje2);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avisosText = new javax.swing.JLabel();
        avisosText1 = new javax.swing.JLabel();
        flechaCont = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        avisosText.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        avisosText.setForeground(new java.awt.Color(255, 255, 255));
        avisosText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(avisosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 560, 100));

        avisosText1.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        avisosText1.setForeground(new java.awt.Color(255, 255, 255));
        avisosText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(avisosText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 560, 100));

        flechaCont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Flecha.png"))); // NOI18N
        flechaCont.setBorder(null);
        flechaCont.setBorderPainted(false);
        flechaCont.setContentAreaFilled(false);
        flechaCont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                flechaContMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                flechaContMouseExited(evt);
            }
        });
        flechaCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flechaContActionPerformed(evt);
            }
        });
        getContentPane().add(flechaCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 230, 70));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Cartel.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 518));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flechaContMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaContMouseEntered
        // TODO add your handling code here:

        flechaCont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Flecha2.png")));

    }//GEN-LAST:event_flechaContMouseEntered

    private void flechaContMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaContMouseExited
        // TODO add your handling code here:

        flechaCont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Flecha.png")));

    }//GEN-LAST:event_flechaContMouseExited

    private void flechaContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flechaContActionPerformed
        // TODO add your handling code here:
        setVisible(false);

    }//GEN-LAST:event_flechaContActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisosText;
    private javax.swing.JLabel avisosText1;
    private javax.swing.JButton flechaCont;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
